##########################################################################
# Modify all parameters related to joystickk to servo here
##########################################################################

# Setup for Microsoft Xbox 360 Wired Controller
enable_joint_commands_button: 4  # LB
enable_twist_commands_button: 5  # RB
switch_cartesian_command_frame_button: 1   # B
switch_joint_axis_mode_button: 2  # X

cartesian_command_frames:
  - base_link
  - tool0
  - world

joints:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7

# Do not change this names. The joints are order as in the list above
num_joint_axis_control_modes: 2
joint1_axis:
  - "1": 0          # Left/Right Axis stick left
joint2_axis:
  - "1": 1           # Up/Down Axis stick left
joint3_axis:
 - 1: 6           # cross key left/right
 - 2: 0           # Left/Right Axis stick left
joint4_axis:
 - 1: 7           # cross key up/down
 - 2: 1           # Up/Down Axis stick left
joint5_axis:
 - 1: 3           # Left/Right Axis stick right
joint6_axis:
 - 1: 4           # Up/Down Axis stick right
joint7_axis:
 - 2: 3           # Left/Right Axis stick right

# Alternative parameters with only one control mode
#num_joint_axis_control_modes: 1
#joint1_axis: 0  # Left/Right Axis stick left
#joint2_axis: 1  # Up/Down Axis stick left
#joint3_axis: 6  # cross key left/right
#joint4_axis: 7  # cross key up/down
#joint5_axis: 3  # Left/Right Axis stick right
#joint6_axis: 4  # Up/Down Axis stick right
